In [8]:
import pandas as pd

In [9]:
data= { 
    "Name": ["Mohini","Harshal","Arjun","Yogita","Anil","Shubham","Akshita"],
    "Age" : [23,42,52,27,28,29,20],
    "City":["Nagpur","Banglore","Pune","Hyderabad","Mumbai","Surat","Lucknow"],
    "Python_Marks":[90,98,96,94,80,81,87],
    "SQL Marks":[78,79,80,76,75,74,73],
    "Attendance":[90,91,92,93,94,95,96],

}
df=pd.DataFrame(data)
print(df)

      Name  Age       City  Python_Marks  SQL Marks  Attendance
0   Mohini   23     Nagpur            90         78          90
1  Harshal   42   Banglore            98         79          91
2    Arjun   52       Pune            96         80          92
3   Yogita   27  Hyderabad            94         76          93
4     Anil   28     Mumbai            80         75          94
5  Shubham   29      Surat            81         74          95
6  Akshita   20    Lucknow            87         73          96

In [10]:
print(df.head())

      Name  Age       City  Python_Marks  SQL Marks  Attendance
0   Mohini   23     Nagpur            90         78          90
1  Harshal   42   Banglore            98         79          91
2    Arjun   52       Pune            96         80          92
3   Yogita   27  Hyderabad            94         76          93
4     Anil   28     Mumbai            80         75          94

In [11]:
print(df.tail())

      Name  Age       City  Python_Marks  SQL Marks  Attendance
2    Arjun   52       Pune            96         80          92
3   Yogita   27  Hyderabad            94         76          93
4     Anil   28     Mumbai            80         75          94
5  Shubham   29      Surat            81         74          95
6  Akshita   20    Lucknow            87         73          96

In [12]:
print(df.shape)

(7, 6)

In [13]:
print(df.columns)

Index(['Name', 'Age', 'City', 'Python_Marks', 'SQL Marks', 'Attendance'], dtype='str')

In [14]:
print(df.dtypes)

Name              str
Age             int64
City              str
Python_Marks    int64
SQL Marks       int64
Attendance      int64
dtype: object

these all process are called as BASIC INSPECTION

In [15]:
print(df["Name"])

0     Mohini
1    Harshal
2      Arjun
3     Yogita
4       Anil
5    Shubham
6    Akshita
Name: Name, dtype: str

In [16]:
print(df["Age"])

0    23
1    42
2    52
3    27
4    28
5    29
6    20
Name: Age, dtype: int64

In [17]:
print(df["City"])

0       Nagpur
1     Banglore
2         Pune
3    Hyderabad
4       Mumbai
5        Surat
6      Lucknow
Name: City, dtype: str

In [19]:
print(df[["Name","Python_Marks","SQL Marks","Attendance"]])

      Name  Python_Marks  SQL Marks  Attendance
0   Mohini            90         78          90
1  Harshal            98         79          91
2    Arjun            96         80          92
3   Yogita            94         76          93
4     Anil            80         75          94
5  Shubham            81         74          95
6  Akshita            87         73          96

In [ ]:
print(df[df["City"]=="Pune"])

    Name  Age  City  Python_Marks  SQL Marks  Attendance
2  Arjun   52  Pune            96         80          92

In [ ]:
print(df[df["Python_Marks"]>=80])

      Name  Age       City  Python_Marks  SQL Marks  Attendance
0   Mohini   23     Nagpur            90         78          90
1  Harshal   42   Banglore            98         79          91
2    Arjun   52       Pune            96         80          92
3   Yogita   27  Hyderabad            94         76          93
4     Anil   28     Mumbai            80         75          94
5  Shubham   29      Surat            81         74          95
6  Akshita   20    Lucknow            87         73          96

In [33]:
print(df[(df["City"]=="Pune")&(df["Python_Marks"]>=80)])

    Name  Age  City  Python_Marks  SQL Marks  Attendance
2  Arjun   52  Pune            96         80          92

#ADVANCE FILTER
#df.sort_values() for data arrangement

In [34]:
df.sort_values("Python_Marks")

      Name  Age       City  Python_Marks  SQL Marks  Attendance
4     Anil   28     Mumbai            80         75          94
5  Shubham   29      Surat            81         74          95
6  Akshita   20    Lucknow            87         73          96
0   Mohini   23     Nagpur            90         78          90
3   Yogita   27  Hyderabad            94         76          93
2    Arjun   52       Pune            96         80          92
1  Harshal   42   Banglore            98         79          91

In [37]:
df.sort_values("SQL Marks")

      Name  Age       City  Python_Marks  SQL Marks  Attendance
6  Akshita   20    Lucknow            87         73          96
5  Shubham   29      Surat            81         74          95
4     Anil   28     Mumbai            80         75          94
3   Yogita   27  Hyderabad            94         76          93
0   Mohini   23     Nagpur            90         78          90
1  Harshal   42   Banglore            98         79          91
2    Arjun   52       Pune            96         80          92

In [38]:
df.sort_values("Python_Marks",ascending=False)

      Name  Age       City  Python_Marks  SQL Marks  Attendance
1  Harshal   42   Banglore            98         79          91
2    Arjun   52       Pune            96         80          92
3   Yogita   27  Hyderabad            94         76          93
0   Mohini   23     Nagpur            90         78          90
6  Akshita   20    Lucknow            87         73          96
5  Shubham   29      Surat            81         74          95
4     Anil   28     Mumbai            80         75          94

In [39]:
df.sort_values("Python_Marks",ascending=True)

      Name  Age       City  Python_Marks  SQL Marks  Attendance
4     Anil   28     Mumbai            80         75          94
5  Shubham   29      Surat            81         74          95
6  Akshita   20    Lucknow            87         73          96
0   Mohini   23     Nagpur            90         78          90
3   Yogita   27  Hyderabad            94         76          93
2    Arjun   52       Pune            96         80          92
1  Harshal   42   Banglore            98         79          91