In [26]:
# import pandas as pd

PANDAS PRACTICAL ASSESSMENT

In [27]:
# test= { 
#     "Patient_Id": ["Mohini","Shubham","Akshita"],
#     "Age" : [23,42,52],
#     "Surgery_type":["kidney","Heart","Cancer"]
# }
# df=pd.DataFrame(test)
# print(df)

PART A – Create a DataFrame (5 Marks)

In [1]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

1

In [29]:
print(df.head(5))

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned

2

In [30]:
print(df[["Patient_ID","City","Surgery_Type","Admission_Type"]])

  Patient_ID        City      Surgery_Type Admission_Type
0       P101   Hyderabad   Cholecystectomy        Planned
1       P102    Warangal              CABG      Emergency
2       P103   Hyderabad      Appendectomy      Emergency
3       P104  Vijayawada     Hernia Repair        Planned
4       P105   Hyderabad  Knee Replacement        Planned
5       P106   Nizamabad              PTCA      Emergency
6       P107   Hyderabad      Appendectomy      Emergency
7       P108    Warangal   Cholecystectomy        Planned
8       P109   Hyderabad     Hernia Repair        Planned
9       P110  Karimnagar  Knee Replacement        Planned

3

In [ ]:

print(df[df["Admission_Type"]=="Emergency"])

  Patient_ID  Age       City  Surgery_Type  Operation_Duration_Min  \
1       P102   62   Warangal          CABG                     240
2       P103   34  Hyderabad  Appendectomy                      75
5       P106   68  Nizamabad          PTCA                     150
6       P107   29  Hyderabad  Appendectomy                      70

   Length_of_Stay_Days Admission_Type
1                    7      Emergency
2                    1      Emergency
5                    4      Emergency
6                    1      Emergency

4

In [32]:
print(df[df["Operation_Duration_Min"]>=80])

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
7       P108   52    Warangal   Cholecystectomy                      95
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
7                    2        Planned
8                    3        Planned
9                    6        Planned

5

In [33]:
print(df[df["City"]=="Hyderabad"] [["Patient_ID","City","Surgery_Type","Admission_Type"]])

  Patient_ID       City      Surgery_Type Admission_Type
0       P101  Hyderabad   Cholecystectomy        Planned
2       P103  Hyderabad      Appendectomy      Emergency
4       P105  Hyderabad  Knee Replacement        Planned
6       P107  Hyderabad      Appendectomy      Emergency
8       P109  Hyderabad     Hernia Repair        Planned

6

In [34]:
df["Operation_Duration_Min"].mean()

np.float64(133.0)

7

In [18]:
df["Operation_Duration_Min"].max()

np.int64(240)

8

In [ ]:
# df["Operation_Duration_Min"].max()==print(df[df["Operation_Duration_Min"]>=80])

9

In [19]:
print(df[(df["Operation_Duration_Min"]>=100)&(df["Length_of_Stay_Days"]>=3)])

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
1       P102   62    Warangal              CABG                     240
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
1                    7      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
8                    3        Planned
9                    6        Planned

10

In [20]:
print(df[df["Operation_Duration_Min"]>=100])

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
1       P102   62    Warangal              CABG                     240
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
1                    7      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
8                    3        Planned
9                    6        Planned

PART C – Interview-Style Business Challenge (5 Marks)

In [21]:
df[(df['Operation_Duration_Min'] > 100) & (df['Length_of_Stay_Days'] > 3)][['Patient_ID', 'Surgery_Type']]

  Patient_ID      Surgery_Type
1       P102              CABG
4       P105  Knee Replacement
5       P106              PTCA
9       P110  Knee Replacement

#newdata

<!-- new cell -->

In [1]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

<!-- Loc label/condition ke basis me per data select karna hai -->

# Loc label/condition ke basis me per data select karna hai

In [2]:
df.loc[3]

Patient_ID                         P104
Age                                  55
City                         Vijayawada
Surgery_Type              Hernia Repair
Operation_Duration_Min              110
Length_of_Stay_Days                   3
Admission_Type                  Planned
Name: 3, dtype: object

In [3]:
df.loc[0]

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [4]:
df.loc[0,"Patient_ID"]

'P101'

In [5]:
df.loc[:,["Patient_ID","Surgery_Type"]]

  Patient_ID      Surgery_Type
0       P101   Cholecystectomy
1       P102              CABG
2       P103      Appendectomy
3       P104     Hernia Repair
4       P105  Knee Replacement
5       P106              PTCA
6       P107      Appendectomy
7       P108   Cholecystectomy
8       P109     Hernia Repair
9       P110  Knee Replacement

In [ ]:
# :- used for all rows with colummns according to the columns

In [7]:
df.loc[df["City"]=="Hyderabad"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned

In [8]:
df.loc[df["City"]=="Hyderabad"][["Patient_ID","Surgery_Type","Admission_Type"]]

  Patient_ID      Surgery_Type Admission_Type
0       P101   Cholecystectomy        Planned
2       P103      Appendectomy      Emergency
4       P105  Knee Replacement        Planned
6       P107      Appendectomy      Emergency
8       P109     Hernia Repair        Planned

In [ ]:
# loc : label/condition based column name use df.loc[0,"City"], use for business filtering
# iloc : basis on indexing, and position . first 3 rows and first 3 columns

In [2]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [3]:
df.iloc[0]

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [4]:
df.loc[0]

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [5]:
df.iloc[1]

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object

In [ ]:
df.iloc[0,0]  #specific rows and columns

'P101'

In [9]:
df.iloc[0,3] #first rows , 3rd column

'Cholecystectomy'

In [10]:
df.iloc[0:3] #first 3 row

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency

In [8]:
df.iloc[0:3,0:3] #first 3 rows + #first 3 columns

  Patient_ID  Age       City
0       P101   45  Hyderabad
1       P102   62   Warangal
2       P103   34  Hyderabad

In [11]:
df.iloc[0:5,0:5]

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180

In [12]:
# index 2 wali patient ki complete info chaiye
df.iloc[1]

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object

In [13]:
# third patient ki complete info chaiye 
df.iloc[2]

Patient_ID                        P103
Age                                 34
City                         Hyderabad
Surgery_Type              Appendectomy
Operation_Duration_Min              75
Length_of_Stay_Days                  1
Admission_Type               Emergency
Name: 2, dtype: object

In [ ]:
# question : what is the main differecne between the loc and the iloc
# Answer : # loc : label/condition based column name use df.loc[0,"City"], use for business filtering
# iloc : basis on indexing, and integer position . first 3 rows and first 3 columns

In [16]:
# Que 1 : The hospital wants to check the details of the 4th patient 
df.iloc[3]

Patient_ID                         P104
Age                                  55
City                         Vijayawada
Surgery_Type              Hernia Repair
Operation_Duration_Min              110
Length_of_Stay_Days                   3
Admission_Type                  Planned
Name: 3, dtype: object

In [17]:
# Que 2 : find the Patient who's index label is 7
df.iloc[7]

Patient_ID                           P108
Age                                    52
City                             Warangal
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 95
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 7, dtype: object

In [ ]:
# Que 3 : display the first 5 patients, show only---patient_id , city , age
df.loc[0:5 , ["Patient_ID","City","Age"]]

  Patient_ID        City  Age
0       P101   Hyderabad   45
1       P102    Warangal   62
2       P103   Hyderabad   34
3       P104  Vijayawada   55
4       P105   Hyderabad   41
5       P106   Nizamabad   68

In [26]:
# Que 4 : diplay last three patients data
df.loc[7:9]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [29]:
# Que 5 : patient id and city
df.loc[0:9 ,["Patient_ID","City"]]

  Patient_ID        City
0       P101   Hyderabad
1       P102    Warangal
2       P103   Hyderabad
3       P104  Vijayawada
4       P105   Hyderabad
5       P106   Nizamabad
6       P107   Hyderabad
7       P108    Warangal
8       P109   Hyderabad
9       P110  Karimnagar

In [11]:
# Que 6 : find all the patient from wrangel display patient id and surgery.age
df.loc[df["City"] == "Warangal", ["Patient_ID", "Surgery_Type"]]

NameError: name 'df' is not defined

In [ ]:
# Que 7 : find patients whose age is greater than 50 , patient id , age , city

In [14]:
# Que 8 : rows 2 to 5 and  column 1 to 4

In [15]:
# Que 9: patient at index 4 patient id , surgery type

In [ ]:
# challenge : find the youngest emergency patient , patient id , age , city